(cl:in-package communicator_pkg-msg)
(cl:export '(THROTTLE-VAL
          THROTTLE
          FR-VAL
          FR
          FL-VAL
          FL
          CR-VAL
          CR
          CL-VAL
          CL
          BR-VAL
          BR
          BL-VAL
          BL
          CB-VAL
          CB
          YAW-VAL
          YAW
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          DEPTH-VAL
          DEPTH
          STEPPER-VAL
          STEPPER
          PNEUMATIC-VAL
          PNEUMATIC
          PID_DEPTHMODE-VAL
          PID_DEPTHMODE
          PID_STABILIZEMODE-VAL
          PID_STABILIZEMODE
          MONITOR_STP_ROLL-VAL
          MONITOR_STP_ROLL
          MONITOR_STP_PITCH-VAL
          MONITOR_STP_PITCH
          MONITOR_STP_YAW-VAL
          MONITOR_STP_YAW
          MONITOR_STP_DEPTH-VAL
          MONITOR_STP_DEPTH
          MISSION1_MODE-VAL
          MISSION1_MODE
          MISSION2_MODE-VAL
          MISSION2_MODE
          MISSION3_STATUS-VAL
          MISSION3_STATUS
          MISSION4_STATUS-VAL
          MISSION4_STATUS
))