(cl:in-package master_package-msg)
(cl:export '(VOLTAGE-VAL
          VOLTAGE
          PRESSURE-VAL
          PRESSURE
          TEMPERATURE-VAL
          TEMPERATURE
          ACTUAL_DEPTH-VAL
          ACTUAL_DEPTH
          ACTUAL_ROLL-VAL
          ACTUAL_ROLL
          ACTUAL_PITCH-VAL
          ACTUAL_PITCH
          ACTUAL_YAW-VAL
          ACTUAL_YAW
          ISAUTONOMOUS-VAL
          ISAUTONOMOUS
          KP_ROLL-VAL
          KP_ROLL
          KI_ROLL-VAL
          KI_ROLL
          KD_ROLL-VAL
          KD_ROLL
          TARGET_STP_ROLL-VAL
          TARGET_STP_ROLL
          MONITOR_STP_ROLL-VAL
          MONITOR_STP_ROLL
          KP_PITCH-VAL
          KP_PITCH
          KI_PITCH-VAL
          KI_PITCH
          KD_PITCH-VAL
          KD_PITCH
          TARGET_STP_PITCH-VAL
          TARGET_STP_PITCH
          MONITOR_STP_PITCH-VAL
          MONITOR_STP_PITCH
          KP_YAW-VAL
          KP_YAW
          KI_YAW-VAL
          KI_YAW
          KD_YAW-VAL
          KD_YAW
          TARGET_STP_YAW-VAL
          TARGET_STP_YAW
          MONITOR_STP_YAW-VAL
          MONITOR_STP_YAW
          KP_DEPTH-VAL
          KP_DEPTH
          KI_DEPTH-VAL
          KI_DEPTH
          KD_DEPTH-VAL
          KD_DEPTH
          TARGET_STP_DEPTH-VAL
          TARGET_STP_DEPTH
          MONITOR_STP_DEPTH-VAL
          MONITOR_STP_DEPTH
          ISROLLLOCKED-VAL
          ISROLLLOCKED
          ISYAWLOCKED-VAL
          ISYAWLOCKED
          ISPITCHLOCKED-VAL
          ISPITCHLOCKED
          ISDEPTHLOCKED-VAL
          ISDEPTHLOCKED
          THROTTLE-VAL
          THROTTLE
          THRUSTER_FR-VAL
          THRUSTER_FR
          THRUSTER_FL-VAL
          THRUSTER_FL
          THRUSTER_CR-VAL
          THRUSTER_CR
          THRUSTER_CL-VAL
          THRUSTER_CL
          THRUSTER_BR-VAL
          THRUSTER_BR
          THRUSTER_BL-VAL
          THRUSTER_BL
          THRUSTER_BC-VAL
          THRUSTER_BC
          PID_DEPTHMODE-VAL
          PID_DEPTHMODE
          PID_STABILIZEMODE-VAL
          PID_STABILIZEMODE
          MISSION1_MODE-VAL
          MISSION1_MODE
          MISSION2_MODE-VAL
          MISSION2_MODE
          MISSION3_STATUS-VAL
          MISSION3_STATUS
          MISSION4_STATUS-VAL
          MISSION4_STATUS
          STEPPER_DEGREE-VAL
          STEPPER_DEGREE
          PNEUMATIC_STATUS-VAL
          PNEUMATIC_STATUS
))