(cl:in-package master_package-msg)
(cl:export '(ISROLLLOCKED-VAL
          ISROLLLOCKED
          ISYAWLOCKED-VAL
          ISYAWLOCKED
          ISPITCHLOCKED-VAL
          ISPITCHLOCKED
          ISDEPTHLOCKED-VAL
          ISDEPTHLOCKED
          KP_ROLL-VAL
          KP_ROLL
          KI_ROLL-VAL
          KI_ROLL
          KD_ROLL-VAL
          KD_ROLL
          TARGET_STP_ROLL-VAL
          TARGET_STP_ROLL
          KP_PITCH-VAL
          KP_PITCH
          KI_PITCH-VAL
          KI_PITCH
          KD_PITCH-VAL
          KD_PITCH
          TARGET_STP_PITCH-VAL
          TARGET_STP_PITCH
          KP_YAW-VAL
          KP_YAW
          KI_YAW-VAL
          KI_YAW
          KD_YAW-VAL
          KD_YAW
          TARGET_STP_YAW-VAL
          TARGET_STP_YAW
          KP_DEPTH-VAL
          KP_DEPTH
          KI_DEPTH-VAL
          KI_DEPTH
          KD_DEPTH-VAL
          KD_DEPTH
          TARGET_STP_DEPTH-VAL
          TARGET_STP_DEPTH
          LEFTX-VAL
          LEFTX
          LEFTY-VAL
          LEFTY
          RIGHTX-VAL
          RIGHTX
          RIGHTY-VAL
          RIGHTY
          R1-VAL
          R1
          R2-VAL
          R2
          L1-VAL
          L1
          L2-VAL
          L2
          ISGYCALIBRATE-VAL
          ISGYCALIBRATE
))