# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from toggle_pkg/finalJoy.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class finalJoy(genpy.Message):
  _md5sum = "3d20946d4d46cc16c1a33df6866b61f3"
  _type = "toggle_pkg/finalJoy"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """string leftX
string leftY
string rightX
string rightY
string alter_right_x
string alter_right_y
string R1
string R2
string L1
string L2
string btn_triangle
string btn_square
string btn_circle
string btn_cross
string AutonomMode
string PID_DepthMode
string PID_StabilizeMode
string throttle

# Circle
string Mission1_Mode 
# Cross
string Mission2_Mode
# Start
string Mission3_Status
# Select
string Mission4_Status """
  __slots__ = ['leftX','leftY','rightX','rightY','alter_right_x','alter_right_y','R1','R2','L1','L2','btn_triangle','btn_square','btn_circle','btn_cross','AutonomMode','PID_DepthMode','PID_StabilizeMode','throttle','Mission1_Mode','Mission2_Mode','Mission3_Status','Mission4_Status']
  _slot_types = ['string','string','string','string','string','string','string','string','string','string','string','string','string','string','string','string','string','string','string','string','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       leftX,leftY,rightX,rightY,alter_right_x,alter_right_y,R1,R2,L1,L2,btn_triangle,btn_square,btn_circle,btn_cross,AutonomMode,PID_DepthMode,PID_StabilizeMode,throttle,Mission1_Mode,Mission2_Mode,Mission3_Status,Mission4_Status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(finalJoy, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.leftX is None:
        self.leftX = ''
      if self.leftY is None:
        self.leftY = ''
      if self.rightX is None:
        self.rightX = ''
      if self.rightY is None:
        self.rightY = ''
      if self.alter_right_x is None:
        self.alter_right_x = ''
      if self.alter_right_y is None:
        self.alter_right_y = ''
      if self.R1 is None:
        self.R1 = ''
      if self.R2 is None:
        self.R2 = ''
      if self.L1 is None:
        self.L1 = ''
      if self.L2 is None:
        self.L2 = ''
      if self.btn_triangle is None:
        self.btn_triangle = ''
      if self.btn_square is None:
        self.btn_square = ''
      if self.btn_circle is None:
        self.btn_circle = ''
      if self.btn_cross is None:
        self.btn_cross = ''
      if self.AutonomMode is None:
        self.AutonomMode = ''
      if self.PID_DepthMode is None:
        self.PID_DepthMode = ''
      if self.PID_StabilizeMode is None:
        self.PID_StabilizeMode = ''
      if self.throttle is None:
        self.throttle = ''
      if self.Mission1_Mode is None:
        self.Mission1_Mode = ''
      if self.Mission2_Mode is None:
        self.Mission2_Mode = ''
      if self.Mission3_Status is None:
        self.Mission3_Status = ''
      if self.Mission4_Status is None:
        self.Mission4_Status = ''
    else:
      self.leftX = ''
      self.leftY = ''
      self.rightX = ''
      self.rightY = ''
      self.alter_right_x = ''
      self.alter_right_y = ''
      self.R1 = ''
      self.R2 = ''
      self.L1 = ''
      self.L2 = ''
      self.btn_triangle = ''
      self.btn_square = ''
      self.btn_circle = ''
      self.btn_cross = ''
      self.AutonomMode = ''
      self.PID_DepthMode = ''
      self.PID_StabilizeMode = ''
      self.throttle = ''
      self.Mission1_Mode = ''
      self.Mission2_Mode = ''
      self.Mission3_Status = ''
      self.Mission4_Status = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.leftX
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.leftY
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.rightX
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.rightY
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.alter_right_x
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.alter_right_y
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.R1
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.R2
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.L1
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.L2
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.btn_triangle
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.btn_square
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.btn_circle
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.btn_cross
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.AutonomMode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.PID_DepthMode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.PID_StabilizeMode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.throttle
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mission1_Mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mission2_Mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mission3_Status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mission4_Status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.leftX = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.leftX = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.leftY = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.leftY = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.rightX = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.rightX = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.rightY = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.rightY = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.alter_right_x = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.alter_right_x = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.alter_right_y = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.alter_right_y = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.R1 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.R1 = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.R2 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.R2 = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.L1 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.L1 = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.L2 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.L2 = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.btn_triangle = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.btn_triangle = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.btn_square = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.btn_square = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.btn_circle = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.btn_circle = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.btn_cross = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.btn_cross = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.AutonomMode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.AutonomMode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.PID_DepthMode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.PID_DepthMode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.PID_StabilizeMode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.PID_StabilizeMode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.throttle = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.throttle = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mission1_Mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mission1_Mode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mission2_Mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mission2_Mode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mission3_Status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mission3_Status = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mission4_Status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mission4_Status = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.leftX
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.leftY
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.rightX
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.rightY
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.alter_right_x
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.alter_right_y
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.R1
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.R2
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.L1
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.L2
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.btn_triangle
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.btn_square
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.btn_circle
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.btn_cross
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.AutonomMode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.PID_DepthMode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.PID_StabilizeMode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.throttle
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mission1_Mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mission2_Mode
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mission3_Status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.Mission4_Status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.leftX = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.leftX = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.leftY = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.leftY = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.rightX = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.rightX = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.rightY = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.rightY = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.alter_right_x = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.alter_right_x = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.alter_right_y = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.alter_right_y = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.R1 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.R1 = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.R2 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.R2 = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.L1 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.L1 = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.L2 = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.L2 = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.btn_triangle = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.btn_triangle = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.btn_square = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.btn_square = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.btn_circle = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.btn_circle = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.btn_cross = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.btn_cross = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.AutonomMode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.AutonomMode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.PID_DepthMode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.PID_DepthMode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.PID_StabilizeMode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.PID_StabilizeMode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.throttle = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.throttle = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mission1_Mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mission1_Mode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mission2_Mode = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mission2_Mode = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mission3_Status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mission3_Status = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.Mission4_Status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.Mission4_Status = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
