isDepthLocked: false
isPitchLocked: false
isRollLocked: false
isYawLocked: false
kd_depth: 200
kd_pitch: 50
kd_roll: 50
kd_yaw: 90
ki_depth: 0
ki_pitch: 0
ki_roll: 0
ki_yaw: 0
kp_depth: 70
kp_pitch: 20
kp_roll: 10
kp_yaw: 15
target_stp_depth: 0
target_stp_pitch: 0
target_stp_roll: 0
target_stp_yaw: 0
