(cl:in-package toggle_pkg-msg)
(cl:export '(LEFTX-VAL
          LEFTX
          LEFTY-VAL
          LEFTY
          RIGHTX-VAL
          RIGHTX
          RIGHTY-VAL
          RIGHTY
          ALTER_RIGHT_X-VAL
          ALTER_RIGHT_X
          ALTER_RIGHT_Y-VAL
          ALTER_RIGHT_Y
          R1-VAL
          R1
          R2-VAL
          R2
          L1-VAL
          L1
          L2-VAL
          L2
          BTN_TRIANGLE-VAL
          BTN_TRIANGLE
          BTN_SQUARE-VAL
          BTN_SQUARE
          BTN_CIRCLE-VAL
          BTN_CIRCLE
          BTN_CROSS-VAL
          BTN_CROSS
          AUTONOMMODE-VAL
          AUTONOMMODE
          PID_DEPTHMODE-VAL
          PID_DEPTHMODE
          PID_STABILIZEMODE-VAL
          PID_STABILIZEMODE
          THROTTLE-VAL
          THROTTLE
          MISSION1_MODE-VAL
          MISSION1_MODE
          MISSION2_MODE-VAL
          MISSION2_MODE
          MISSION3_STATUS-VAL
          MISSION3_STATUS
          MISSION4_STATUS-VAL
          MISSION4_STATUS
))