// Generated by gencpp from file gripper_pkg/Gripper.msg
// DO NOT EDIT!


#ifndef GRIPPER_PKG_MESSAGE_GRIPPER_H
#define GRIPPER_PKG_MESSAGE_GRIPPER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace gripper_pkg
{
template <class ContainerAllocator>
struct Gripper_
{
  typedef Gripper_<ContainerAllocator> Type;

  Gripper_()
    : gripper_state(0)  {
    }
  Gripper_(const ContainerAllocator& _alloc)
    : gripper_state(0)  {
  (void)_alloc;
    }



   typedef int64_t _gripper_state_type;
  _gripper_state_type gripper_state;





  typedef boost::shared_ptr< ::gripper_pkg::Gripper_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gripper_pkg::Gripper_<ContainerAllocator> const> ConstPtr;

}; // struct Gripper_

typedef ::gripper_pkg::Gripper_<std::allocator<void> > Gripper;

typedef boost::shared_ptr< ::gripper_pkg::Gripper > GripperPtr;
typedef boost::shared_ptr< ::gripper_pkg::Gripper const> GripperConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gripper_pkg::Gripper_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gripper_pkg::Gripper_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gripper_pkg::Gripper_<ContainerAllocator1> & lhs, const ::gripper_pkg::Gripper_<ContainerAllocator2> & rhs)
{
  return lhs.gripper_state == rhs.gripper_state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gripper_pkg::Gripper_<ContainerAllocator1> & lhs, const ::gripper_pkg::Gripper_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gripper_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gripper_pkg::Gripper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gripper_pkg::Gripper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_pkg::Gripper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gripper_pkg::Gripper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_pkg::Gripper_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gripper_pkg::Gripper_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gripper_pkg::Gripper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac317dda7ced7e62be2700631cdc5d29";
  }

  static const char* value(const ::gripper_pkg::Gripper_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac317dda7ced7e62ULL;
  static const uint64_t static_value2 = 0xbe2700631cdc5d29ULL;
};

template<class ContainerAllocator>
struct DataType< ::gripper_pkg::Gripper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gripper_pkg/Gripper";
  }

  static const char* value(const ::gripper_pkg::Gripper_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gripper_pkg::Gripper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 gripper_state\n"
;
  }

  static const char* value(const ::gripper_pkg::Gripper_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gripper_pkg::Gripper_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gripper_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gripper_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gripper_pkg::Gripper_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gripper_pkg::Gripper_<ContainerAllocator>& v)
  {
    s << indent << "gripper_state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.gripper_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GRIPPER_PKG_MESSAGE_GRIPPER_H
